services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID_MAIN}
      - PGID=${UID_MAIN}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${APPDATA}/jellyfin:/config
      - ${APPDATA}/webgrabplus/data:/epg
      - ${STORAGE}/Movies:/Movies
      - ${STORAGE}/TV:/TV
      - ${STORAGE}/Downloads:/Downloads
      - ${STORAGE}/Music:/Music
      - ${TEMP}/transcode:/transcode
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri      
    restart: unless-stopped
